[build]
  command = "yarn build"
  functions = "functions-build" # netlify dev uses this to know where to scaffold and serve your functions
  publish = "build"

# note: each of these fields are OPTIONAL
[dev]
  framework = "#custom"
  command = "yarn start" # Command to start your dev server
  targetPort=3000
  port = 8888 # Port that the dev server will be listening on
  publish = "build" # If you use a _redirect file, provide the path to your static content folder 
  functionsPort = 34567

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200